plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = '0.1.0'
group = 'dev.liquidcatmofu'

base {
    archivesName = 'mtr-1.20.1-patches'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

sourceSets {
    mtrStub {
        java.srcDir 'src/stubs/java'
    }
}
sourceSets.main.compileClasspath += sourceSets.mtrStub.output

tasks.named('compileJava').configure {
    dependsOn tasks.named('compileMtrStubJava')
}

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'info'
            mods {
                mtr_patches {
                    source sourceSets.main
                }
            }
        }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.10'
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : 'mtr_patches',
                'Specification-Vendor'    : 'LiquidCatMofu',
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.version.toString(),
                'Implementation-Vendor'   : 'LiquidCatMofu',
                'MixinConfigs'            : 'mtr_patches.mixins.json'
        ])
    }
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
